In [2]:
import numpy as np

# importe de siniestros anuales por poliza (€)
# np.array me genera un vector, lista de elementos pero numpy
siniestros = np.array([450, 800, 1200, 1500, 2300, 5000])

# exposiciones a riesgo ( años asegurados )
exposicion = np.array([1,1,1,0.5, 2 ,1])

# pesos de cada poliza
pesos = np.array([0.10, 0.15, 0.20, 0.10, 0.25, 0.20])


Funciones estadistica de NUMPY:

np.mean - sinestro medio . Coste medio esperado por poliza

In [2]:
np.mean(siniestros)

np.float64(1875.0)

np.median() - siniestro típico - Valor central, menos afectado por siniestros grandes

In [3]:
np.median(siniestros)

np.float64(1350.0)

np.sum - coste total de la cartera - coste total de sinestros

In [4]:
np.sum(siniestros)

np.int64(11250)

np.std/np.var - volatilidad del riesgo - medida de incertidumbre

In [5]:
np.std(siniestros)

np.float64(1512.6549507405844)

In [6]:
np.var(siniestros)

np.float64(2288125.0)

np.percentile/np.quantile - riesgos extremo (VaR) - que casos superan 5% de riesgo extremo

In [7]:
np.percentile(siniestros, 95)

np.float64(4325.0)

In [8]:
np.quantile(siniestros, 0.95)

np.float64(4325.0)

Segmentación de riesgos - Clasificacion automatica de mi riesgo en funcion la prima
np.where

In [9]:
riesgo = np.where(siniestros > 2000, 'Alto', 'Normal')
print(riesgo)

['Normal' 'Normal' 'Normal' 'Normal' 'Alto' 'Alto']


np.clip - un vector con limite de cobertura - La asegurado solo paga hasta un maximo de 3000. Como quederia el pago de la prima

In [10]:
pago_limitado = np.clip(siniestros, 0, 3000)
print(pago_limitado)

[ 450  800 1200 1500 2300 3000]


np.maximun - deducción - deducir 500 euros de la poliza

In [11]:
valor_deducible = 500
pago = np.maximum(siniestros - valor_deducible, 0)
print(pago)

[   0  300  700 1000 1800 4500]


Media ponderada np.dot(data, ponderacion) - prima con media ponderada

In [12]:
prima_media = np.dot(siniestros, pesos)
print(prima_media)

2130.0


pagos acumulados - Evolución acumulada del coste de los sinistros
np.cumsum(vector)

In [13]:
np.cumsum(siniestros)

array([  450,  1250,  2450,  3950,  6250, 11250])

Frecuencia de sinistros - funcion de poisson - numero de siniestro por poliza al año

In [14]:
np.random.poisson(0.8, 1000)

array([2, 1, 0, 0, 0, 1, 0, 2, 3, 1, 2, 0, 0, 0, 1, 0, 2, 0, 0, 0, 1, 2,
       1, 0, 2, 3, 1, 1, 0, 2, 0, 4, 0, 0, 2, 0, 1, 1, 0, 0, 0, 0, 2, 1,
       0, 2, 0, 0, 1, 0, 3, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 2, 0, 2, 0, 2, 1, 2, 2, 1, 0, 3, 1, 0, 1, 2, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 2, 0, 0, 0, 0, 0,
       0, 2, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 2, 1, 0, 0, 1, 0, 2, 2, 0, 2,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 3, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 2, 2, 1, 1, 1, 1, 0, 1, 0, 1, 1, 2, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 2, 1, 1, 0, 1, 3, 0, 0, 4, 1, 1, 0, 0, 0, 0,
       1, 2, 2, 2, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 2, 1, 4, 0, 0, 0, 0, 2,
       1, 0, 0, 0, 1, 1, 0, 2, 2, 2, 1, 0, 0, 1, 0, 3, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 2, 1, 1, 0, 0, 3, 2, 2, 1, 0, 0, 0, 0, 1, 2, 0, 0, 2,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 2, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 2, 0, 0, 0, 1, 0, 2, 1, 2,

np.power - valor presente a 2 años con un 3% anual

In [ ]:
valor_actual = siniestros / np.power(1.03, 2)
print(valor_actual)

[ 424.16815911  754.07672731 1131.11509096 1413.8938637  2167.97059101
 4712.97954567]


evolucion de la sinestralidad en el timpo usando como referencias la cantidad de siniestros
np.polifit(años, vector)

In [3]:
anios = np.arange(len(siniestros))
tendencia = np.polyfit(anios, siniestros, 0)
print(tendencia)

[1875.]


ranking de riesgos - identificar la polizas mas peligrosas
np.argsort()

In [7]:
ranking = np.argsort(siniestros)[::-1]
print(ranking)

[5 4 3 2 1 0]
